### PR TITLE
fix: show error page in case pubchem query fails

### LINKED ISSUE #14: unhandled error in pubchem page
https://direct.lactame.com/react/views/HEAD/chemistry/pubchem.html?smiles=COOOOOOOOOOC

### PR DESCRIPTION
**Pull request by kjappelbaum**
check if we have the data object in the result from the call to the pubchem library, if not throw error, closes #14

### CODE REVIEW

File: src/components/chemistry/pubchem/index.tsx [hunk 1]
```diff
@@ -23,6 +23,10 @@ export default function Pubchem(props: { smiles: string }) {
     async () => {
       const compound = await Compound.fromSmiles(smiles);
       const data = await compound.getData();
+
+      if (!(typeof data.data === 'object')) {
```
Comment (targos) [inline src/components/chemistry/pubchem/index.tsx:27]:
```suggestion
      if (typeof data.data !== 'object') {
```
